apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: humangov-prod
namePrefix: prod-texas-
commonLabels:
  environment: prod
  state: texas

images:
  - name: IMAGE_PLACEHOLDER
    newName: 211125586061.dkr.ecr.us-east-1.amazonaws.com/humangov-app
    newTag: v1.0.0  # Stable Tag

patches:
  # Inject REAL texas values from Terraform Output
  - target:
      kind: Deployment
      name: humangov-python-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "humangov-texas-s3-v6k0" 
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "humangov-texas-dynamodb"
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "texas"