apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: humangov-cpu-scaler
  namespace: humangov-dev
spec:
  scaleTargetRef:
    name: humangov-python-app
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50" # Scale up if CPU usage > 50%