apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: humangov-dev
namePrefix: dev-
commonLabels:
  environment: dev

images:
  - name: IMAGE_PLACEHOLDER
    # Your Real ECR URL
    newName: 211125586061.dkr.ecr.us-east-1.amazonaws.com/humangov-app
    # Your Real Image Tag (Notice the colon and quotes!)
    newTag: "2b0b638"

patches:
  # PATCH 1: Deployment Env Vars
  - target:
      kind: Deployment
      name: humangov-python-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        # ⚠️ CHECK: Is this your real bucket name from terraform output?
        value: "humangov-california-s3-13th" 
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "humangov-california-dynamodb"
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "california"

  # PATCH 2: Ingress Hostname
  - target:
      kind: Ingress
      name: humangov-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "dev.humangovv.click"