apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: humangov-dev
namePrefix: dev-
commonLabels:
  environment: dev

    # ⚠️ REPLACE with your real ECR URL
    # ⚠️ REPLACE with your real Tag (or let CI update it)
images:
- name: IMAGE_PLACEHOLDER
  newName: 211125586061.dkr.ecr.us-east-1.amazonaws.com/humangov-app
  newTag: a8141fb
- name: humangov-app
  newName: 211125586061.dkr.ecr.us-east-1.amazonaws.com/humangov-app
  newTag: bedebde

  # Patch 1: Deployment Env Vars

  # Patch 2: Ingress Hostname

  # Patch 3: Nginx Config (Service Discovery)
                # Points to the DEV service
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "humangov-california-s3-9e1r"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "humangov-california-dynamodb"
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "california"
  target:
    kind: Deployment
    name: humangov-python-app
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "dev.humangovv.click"
  target:
    kind: Ingress
    name: humangov-ingress
- patch: |-
    - op: replace
      path: /data/nginx.conf
      value: |
        events {
          worker_connections 1024;
        }
        http {
          server {
            listen 80;
            location / {
              # Points to the DEV service
              proxy_pass http://dev-humangov-python-app-service:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
        }
  target:
    kind: ConfigMap
    name: humangov-nginx-config
